## Logging level
logging:
  level:
    com:
      abanoj:
        scheman: DEBUG
## Database Configuration
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: false
## Exception
server:
  error:
    include-message: always
## Security
application:
  cors:
    allowed-origins: http://localhost:3000
  security:
    jwt:
      expiration: 900000
      refresh:
        expiration: 604800000
      secret-key: ${JWT_SECRET}
  admin:
    email: admin@abanoj.com
    password: ${ADMIN_PASSWORD:admin123}
## Swagger
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /docs
    doc-expansion: list
## Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health, info"