spring:
  application:
    name: scheman
  config:
    import: optional:file:../.env[.properties],optional:file:.env[.properties]
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
## Actuator
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: never
    shutdown:
      enabled: false
  info:
    env:
      enabled: true