## Logging level
logging:
  level:
    root: INFO
    org:
      springframework: WARN
      hibernate:
        SQL: off
## Database Configuration
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
    show-sql: false
## Exception
server:
  error:
    include-message: never
    include-stacktrace: never
## Security
application:
  security:
    jwt:
      expiration: 900000
      refresh:
        expiration: 604800000
      secret-key: ${JWT_SECRET}
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
## Swagger
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
## Actuator
management:
  endpoint:
    health:
      show-details: never
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, metrics